### ISSUE TITLE
Consider dependabot workflow

### ISSUE THREAD

**Issue by dholroyd** [dtolnay/rust-toolchain#113] opened 2024-06-17 20:17 UTC
I have set up the action by pinning its version like so,

```
uses: dtolnay/rust-toolchain@1.76.0
```

Since I use dependabot to update github action versions, I thought this would mean I would have a Rust version that is pinned in my builds, and also that I would receive dependabot PRs for new versions of this action (and therefore of Rust), requiring tests to pass on the next Rust version before the change goes to `main`.

However, since new release branches of `rust-toolchain` are "pre-announced" before the respective Rust release is actually available, this workflow doesn't work.   dependabot currently wants to update my workflow to `dtolnay/rust-toolchain@1.90.0`.

If there is an acceptable way to have releases of new `rust-toolchain` versions trail the respective Rust releases, that would be lovely!  And if that's not possible or is too much effort, than thank you very much for providing `rust-toolchain` anyway.

**Comment by dtolnay** [comment] 2024-06-17 21:02
I think this is a duplicate of #43. For receiving dependabot updates, you would probably want to use a different action than this one.

**Closed by dtolnay** 2024-06-17 21:02 UTC
